In [1]:
import pandas as pd
import re

In [2]:
df = pd.DataFrame(data={'sec1': [60, 120, 180], 'sec2': [30, 60, 90], 'sec3': [10, 20, 30], 'sec1_max': [200, 300, 400], 'timeseries_id': [1, 2, 3]})
df

   sec1  sec2  sec3  sec1_max  timeseries_id
0    60    30    10       200              1
1   120    60    20       300              2
2   180    90    30       400              3

In [16]:
# Step 1: Filter the columns using a regular expression
pattern = r'^sec\d+$'
rho_columns = df.filter(regex=pattern)

# Step 2: Apply the transformation (e.g., divide by 2)
transformed_rho_columns = rho_columns / 60

# # Step 3: Rename the transformed columns
def replace_rho_with_phi(col_name):
    return re.sub(r'^sec(\d+)$', r'min_\1', col_name)

transformed_rho_columns = transformed_rho_columns.rename(columns=replace_rho_with_phi)

# Step 4: Append the transformed columns back to the original DataFrame
df = pd.concat([df, transformed_rho_columns], axis=1)

print(df)

   sec1  sec2  sec3  sec1_max  timeseries_id  min_1  min_2     min_3
0    60    30    10       200              1    1.0    0.5  0.166667
1   120    60    20       300              2    2.0    1.0  0.333333
2   180    90    30       400              3    3.0    1.5  0.500000

In [5]:
list(range(2, 10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
import numpy as np

In [10]:
temp = np.ndarray(0)
temp

array([], dtype=float64)

In [33]:
import pandas as pd

# Sample data for df_original
df = pd.DataFrame({
    'pos1': ['1', '2', '3'],
    'pos2': ['3', '2', '1'],
    'value': [1, 2, 3],
    # add more columns up to pos32
})

# Sample data for df_dict
monocore = pd.DataFrame({
    'monocore': [1, 1, 2, 2, 3, 3],
    'time': [1, 2, 1, 2, 1, 2],
    'keff': [0.9, 0.8, 0.85, 0.75, 0.1, 0.2]
})

In [37]:
combined_id = df['pos1'] + '_' + df['pos2']
df=df.replace({1: 10})
df

  pos1 pos2  value
0    1    3     10
1    2    2      2
2    3    1      3

In [10]:
monocore

   monocore  time  keff
0         1     1  0.90
1         1     2  0.80
2         2     1  0.85
3         2     2  0.75
4         3     1  0.10
5         3     2  0.20

In [38]:
import pandas as pd

# Example DataFrame with categorical and corresponding values
data = {'category': ['A', 'B', 'A', 'C', 'B'],
        'values': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Create dummy variables
dummies = pd.get_dummies(df['category'])

# Multiply dummy variables by the corresponding 'values'
dummies = dummies.mul(df['values'], axis=0)

# Concatenate the dummy variables with the original DataFrame
df = pd.concat([df, dummies], axis=1)

# Drop the original 'category' and 'values' columns
df.drop(['category', 'values'], axis=1, inplace=True)

# Display the result
print(df)

    A   B   C
0  10   0   0
1   0  20   0
2  30   0   0
3   0   0  40
4   0  50   0

In [39]:
df

    A   B   C
0  10   0   0
1   0  20   0
2  30   0   0
3   0   0  40
4   0  50   0

In [45]:
import pandas as pd

# Example DataFrame with 32 columns pos1 to pos32
data = {
    'pos1': [1, 2, 3, 4],
    'pos2': [5, 6, 7, 8],
    'pos3': [1, 2, 3, 4],
    'pos4': [5, 6, 7, 8]
    # Add more columns pos5 to pos32 as needed
}

df = pd.DataFrame(data)

# Initialize an empty DataFrame to store the transformed data
transformed_data = pd.DataFrame()

# Iterate through each column (pos1 to pos32)
for col in df.columns:
    # Get unique values in the current column
    unique_vals = sorted(df[col].unique())
    
    # Create a DataFrame with columns for each unique value
    for val in unique_vals:
        transformed_data[f"{col}_is_{val}"] = (df[col] == val).astype(int) * val

# Display the transformed_data DataFrame
print(transformed_data)

   pos1_is_1  pos1_is_2  pos1_is_3  pos1_is_4  pos2_is_5  pos2_is_6  \
0          1          0          0          0          5          0
1          0          2          0          0          0          6
2          0          0          3          0          0          0
3          0          0          0          4          0          0

   pos2_is_7  pos2_is_8  pos3_is_1  pos3_is_2  pos3_is_3  pos3_is_4  \
0          0          0          1          0          0          0
1          0          0          0          2          0          0
2          7          0          0          0          3          0
3          0          8          0          0          0          4

   pos4_is_5  pos4_is_6  pos4_is_7  pos4_is_8
0          5          0          0          0
1          0          6          0          0
2          0          0          7          0
3          0          0          0          8

In [61]:
import pandas as pd

# Assuming 'df' is your dataframe
# Create a sample dataframe
data = {'A': [1, 2, 150, 3, 4],
        'B': [20, 30, 40, 50, 60]}
df = pd.DataFrame(data)

# Get unique values from the entire dataframe
unique_values = sorted(pd.melt(df).value.unique())

unique_values

[1, 2, 3, 4, 20, 30, 40, 50, 60, 150]

In [62]:
df = pd.DataFrame({
    'pos1': [0, 1, 1],
    'pos2': [1, 1, 1],
    'pos3': [1, 0, 0],
    'pos4': [0, 0, 0]
})
df

   pos1  pos2  pos3  pos4
0     0     1     1     0
1     1     1     0     0
2     1     1     0     0

In [74]:
[f"{col}_1" for col in df.columns.to_numpy()]

['pos1_1', 'pos2_1', 'pos3_1', 'pos4_1']

In [80]:
my_dict = {"layer1": {"neurons": 5, "activation": "mean"}, "layer2": {"neurons": 5, "activation": "mean"}}
my_dict

{'layer1': {'neurons': 5, 'activation': 'mean'},
 'layer2': {'neurons': 5, 'activation': 'mean'}}

In [82]:
for my in my_dict:
    if my == "layer1":
        print("yello")
    else:
        print("meh")

yello
meh

In [85]:
my_dict['layer1']['neurons']

5

In [78]:
df_new = pd.DataFrame()
df_new[[f"{col}_1" for col in df.columns]] = df*10
df_new

   pos1_1  pos2_1  pos3_1  pos4_1
0       0      10      10       0
1      10      10       0       0
2      10      10       0       0